version: 1.4.0.{build}
platform: Any CPU
init:
- ps: >-
    appveyor DownloadFile "https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe"


    Set-Content "c:\program files\postgresql\9.5\data\pg_hba.conf" "host    all             all             ::1/128            trust"


    Add-Content "c:\program files\postgresql\9.5\data\pg_hba.conf" "host    all             all             127.0.0.1/32            trust"


    $env:Path += ";c:\program files\postgresql\9.5\bin"
services: postgresql
install:
- cmd: 
build_script:
- ps: >-
    psql -U postgres -c "CREATE ROLE appveyor LOGIN SUPERUSER CREATEDB CREATEROLE;"


    createdb hangfire_tests



    .nuget\NuGet.exe install .nuget\packages.config -OutputDirectory packages

    powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& {Import-Module '.\packages\psake.*\tools\psake.psm1'; invoke-psake .\psake-project.ps1 -framework "4.6" compile; if ($LastExitCode -and $LastExitCode -ne 0) {write-host "ERROR CODE: $LastExitCode" -fore RED; exit $lastexitcode} }"
